@startuml

title __BALANCING's Class Diagram__\n

  package constants {
    package constants.balancing {
      interface Factors {
          {static} + SECSTAT_INCREASE_MULTIPLIER : double
          {static} + SECSTAT_ROLL_DEVIATION : double
          {static} + MOB_SECSTAT_INCREASE_MULTIPLIER : double
          {static} + PRIMESTAT_INCREASE_MULTIPLIER : double
          {static} + PRIMESTAT_ROLL_DEVIATION : double
          {static} + NUMBER_TO_MAKE_EFFECT_LAST_INFINITLY : int
          {static} + PROBABILITY_TO_SPAWN_A_TERRAIN : float
          {static} + MIN_MOB_LEVEL_FACTOR : float
          {static} + MAX_MOB_LEVEL_FACTOR : float
      }
    }
  }
  

  package constants {
    package constants.balancing {
      interface PropertiesStats {
          {static} + STARTVALUE_FOR_HP_NOT_SPEZIALISED : int
          {static} + SOFTCAP_FOR_HP_NOT_SPEZIALISED_1 : int
          {static} + SOFTCAP_FOR_HP_NOT_SPEZIALISED_2 : int
          {static} + SCALE_1_FOR_HP_NOT_SPEZIALISED : int
          {static} + SCALE_2_FOR_HP_NOT_SPEZIALISED : int
          {static} + SCALE_3_FOR_HP_NOT_SPEZIALISED : int
          {static} + MAX_VALUE_AFTER_SOFTCAP_1_HP_NOT_SPEZIALISED : int
          {static} + MAX_VALUE_AFTER_SOFTCAP_2_HP_NOT_SPEZIALISED : int
          {static} + HP_SCALES_NOT_SPEZIALISED : int[]
          {static} + HP_BASESTATS_NOT_SPEZIALISED : int[]
          {static} + STARTVALUE_FOR_HP_SPEZIALISED : int
          {static} + SOFTCAP_FOR_HP_SPEZIALISED_1 : int
          {static} + SOFTCAP_FOR_HP_SPEZIALISED_2 : int
          {static} + SCALE_1_FOR_HP_SPEZIALISED : int
          {static} + SCALE_2_FOR_HP_SPEZIALISED : int
          {static} + SCALE_3_FOR_HP_SPEZIALISED : int
          {static} + MAX_VALUE_AFTER_SOFTCAP_1_HP_SPEZIALISED : int
          {static} + MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED : int
          {static} + HP_SCALES_SPEZIALISED : int[]
          {static} + HP_BASESTATS_SPEZIALISED : int[]
          {static} + MAX_ACTION_STARTVALUE_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_SOFTCAP_NOT_SPEZIALISED_1 : int
          {static} + MAX_ACTION_SOFTCAP_NOT_SPEZIALISED_2 : int
          {static} + MAX_ACTION_SCALE_1_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_2_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_SCALE_3_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED : int
          {static} + MAX_ACTION_STARTVALUE_SPEZIALISED : int
          {static} + MAX_ACTION_SOFTCAP_SPEZIALISED_1 : int
          {static} + MAX_ACTION_SOFTCAP_SPEZIALISED_2 : int
          {static} + MAX_ACTION_SCALE_1_SPEZIALISED : int
          {static} + MAX_ACTION_SCALE_2_SPEZIALISED : int
          {static} + MAX_ACTION_SCALE_3_SPEZIALISED : int
          {static} + MAX_ACTION_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED : int
          {static} + MAX_ACTION_MAX_VALUE_AFTER_SOFTCAP_2_SPEZIALISED : int
          {static} + ATTACK_RESISTANCE_STARTVALUE_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_NOT_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_NOT_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SCALE_1_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_SCALE_2_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_SCALE_3_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + STM_RESIS_SCALES_NOT_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + STM_RESIS_BASESTATS_NOT_SPEZIALISED_FORTOUGHNESS : int[]
          {static} + ATTACK_RESISTANCE_STARTVALUE_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_SCALE_1_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_SCALE_2_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_SCALE_3_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + STM_RESIS_SCALES_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + STM_RESIS_BASESTATS_SPEZIALISED_FORTOUGHNESS : int[]
          {static} + ATTACK_RESISTANCE_SOFTCAP_NOT_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_NOT_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + ATTACK_RESISTANCE_SCALE_1_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_SCALE_2_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_SCALE_3_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_STRENGTH : float
          {static} + STM_RESIS_SCALES_NOT_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + STM_RESIS_BASES_NOT_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + ATTACK_RESISTANCE_SOFTCAP_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + ATTACK_RESISTANCE_SOFTCAP_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + ATTACK_RESISTANCE_SCALE_1_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_SCALE_2_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_SCALE_3_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_STRENGTH : float
          {static} + ATTACK_RESISTANCE_MAX_VALUE_AFTER_SOFTCAP_2_SPEZIALISED_FOR_STRENGTH : float
          {static} + STM_RESIS_SCALES_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + STM_RESIS_BASES_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + DEFENCE_STARTVALUE_NOT_SPEZIALISED : int
          {static} + DEFENCE_STARTVALUE_SPEZIALISED : int
          {static} + DEFENCE_SOFTCAP_NOT_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + DEFENCE_SOFTCAP_NOT_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_1_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_2_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_3_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALES_NOT_SPEZIALISED_FOR_TOUGHNESS : int[]
          {static} + DEFENCE_BASES_NOT_SPEZIALISED_FOR_TOUGHNESS : int[]
          {static} + DEFENCE_SOFTCAP_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + DEFENCE_SOFTCAP_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_1_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_2_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALE_3_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + DEFENCE_SCALES_SPEZIALISED_FOR_TOUGHNESS : int[]
          {static} + DEFENCE_BASES_SPEZIALISED_FOR_TOUGHNESS : int[]
          {static} + DEFENCE_SOFTCAP_NOT_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + DEFENCE_SOFTCAP_NOT_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_1_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_2_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_3_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALES_NOT_SPEZIALISED_FOR_STRENGTH : int[]
          {static} + DEFENCE_BASES_NOT_SPEZIALISED_FOR_STRENGTH : int[]
          {static} + DEFENCE_SOFTCAP_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + DEFENCE_SOFTCAP_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_1_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_2_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALE_3_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_STRENGTH : int
          {static} + DEFENCE_SCALES_SPEZIALISED_FOR_STRENGTH : int[]
          {static} + DEFENCE_BASES_SPEZIALISED_FOR_STRENGTH : int[]
          {static} + MAGIC_DEFENCE_STARTVALUE_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SOFTCAP_NOT_SPEZIALISED_1 : int
          {static} + MAGIC_DEFENCE_SOFTCAP_NOT_SPEZIALISED_2 : int
          {static} + MAGIC_DEFENCE_SCALE_1_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SCALE_2_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SCALE_3_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_STARTVALUE_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SOFTCAP_SPEZIALISED_1 : int
          {static} + MAGIC_DEFENCE_SOFTCAP_SPEZIALISED_2 : int
          {static} + MAGIC_DEFENCE_SCALE_1_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SCALE_2_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_SCALE_3_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED : int
          {static} + MAGIC_DEFENCE_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED : int
          {static} + ATTACK_STARTVALUE_NOT_SPEZIALISED : int
          {static} + ATTACK_STARTVALUE_SPEZIALISED : int
          {static} + ATTACK_SOFTCAP_NOT_SPEZIALISED_1_FOR_STRENGHT : int
          {static} + ATTACK_SOFTCAP_NOT_SPEZIALISED_2_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_1_NOT_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_2_NOT_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_3_NOT_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALES_NOT_SPEZIALISED_FOR_STRENGHT : int[]
          {static} + ATTACK_BASESTATS_NOT_SPEZIALISED_FOR_STRENGHT : int[]
          {static} + ATTACK_SOFTCAP_SPEZIALISED_1_FOR_STRENGHT : int
          {static} + ATTACK_SOFTCAP_SPEZIALISED_2_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_1_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_2_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALE_3_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_STRENGHT : int
          {static} + ATTACK_SCALES_SPEZIALISED_FOR_STRENGHT : int[]
          {static} + ATTACK_BASESTATS_SPEZIALISED_FOR_STRENGHT : int[]
          {static} + ATTACK_SOFTCAP_NOT_SPEZIALISED_1_FOR_SPEED : int
          {static} + ATTACK_SOFTCAP_NOT_SPEZIALISED_2_FOR_SPEED : int
          {static} + ATTACK_SCALE_1_NOT_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_SCALE_2_NOT_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_SCALE_3_NOT_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_SPEED : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_SPEED : int
          {static} + ATTACK_SCALES_NOT_SPEZIALISED_FOR_SPEED : float[]
          {static} + ATTACK_BASES_NOT_SPEZIALISED_FOR_SPEED : int[]
          {static} + ATTACK_SOFTCAP_SPEZIALISED_1_FOR_SPEED : int
          {static} + ATTACK_SOFTCAP_SPEZIALISED_2_FOR_SPEED : int
          {static} + ATTACK_SCALE_1_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_SCALE_2_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_SCALE_3_SPEZIALISED_FOR_SPEED : float
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_SPEED : int
          {static} + ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_SPEED : int
          {static} + ATTACK_SCALES_SPEZIALISED_FOR_SPEED : float[]
          {static} + ATTACK_BASES_SPEZIALISED_FOR_SPEED : int[]
          {static} + MAGIC_ATTACK_STARTVALUE_NOT_SPEZIALISED : int
          {static} + MAGIC_ATTACK_STARTVALUE_SPEZIALISED : int
          {static} + MAGIC_ATTACK_SOFTCAP_NOT_SPEZIALISED_1_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SOFTCAP_NOT_SPEZIALISED_2_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_1_NOT_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_2_NOT_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_3_NOT_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALES_NOT_SPEZIALISED_FOR_MAGIC : int[]
          {static} + MAGIC_ATTACK_BASES_NOT_SPEZIALISED_FOR_MAGIC : int[]
          {static} + MAGIC_ATTACK_SOFTCAP_SPEZIALISED_1_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SOFTCAP_SPEZIALISED_2_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_1_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_2_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALE_3_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_MAGIC : int
          {static} + MAGIC_ATTACK_SCALES_SPEZIALISED_FOR_MAGIC : int[]
          {static} + MAGIC_ATTACK_BASES_SPEZIALISED_FOR_MAGIC : int[]
          {static} + MAGIC_ATTACK_SOFTCAP_NOT_SPEZIALISED_1_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SOFTCAP_NOT_SPEZIALISED_2_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_1_NOT_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_2_NOT_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_3_NOT_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALES_NOT_SPEZIALISED_FOR_INTELLIGENCE : int[]
          {static} + MAGIC_ATTACK_BASES_NOT_SPEZIALISED_FOR_INTELLIGENCE : int[]
          {static} + MAGIC_ATTACK_SOFTCAP_SPEZIALISED_1_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SOFTCAP_SPEZIALISED_2_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_1_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_2_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALE_3_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_INTELLIGENCE : int
          {static} + MAGIC_ATTACK_SCALES_SPEZIALISED_FOR_INTELLIGENCE : int[]
          {static} + MAGIC_ATTACK_BASES_SPEZIALISED_FOR_INTELLIGENCE : int[]
          {static} + SPEED_STARTVALUE_NOT_SPEZIALISED : int
          {static} + SPEED_SOFTCAP_NOT_SPEZIALISED_1 : int
          {static} + SPEED_SOFTCAP_NOT_SPEZIALISED_2 : int
          {static} + SPEED_SCALE_1_NOT_SPEZIALISED : int
          {static} + SPEED_SCALE_2_NOT_SPEZIALISED : int
          {static} + SPEED_SCALE_3_NOT_SPEZIALISED : int
          {static} + SPEED_MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED : int
          {static} + SPEED_MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED : int
          {static} + SPEED_SCALES_NOT_SPEZIALISED : int[]
          {static} + SPEED_BASES_NOT_SPEZIALISED : int[]
          {static} + SPEED_STARTVALUE_SPEZIALISED : int
          {static} + SPEED_SOFTCAP_SPEZIALISED_1 : int
          {static} + SPEED_SOFTCAP_SPEZIALISED_2 : int
          {static} + SPEED_SCALE_1_SPEZIALISED : int
          {static} + SPEED_SCALE_2_SPEZIALISED : int
          {static} + SPEED_SCALE_3_SPEZIALISED : int
          {static} + SPEED_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED : int
          {static} + SPEED_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED : int
          {static} + SPEED_SCALES_SPEZIALISED : int[]
          {static} + SPEED_BASES_SPEZIALISED : int[]
          {static} + MAX_LOAD_STARTVALUE : int
          {static} + MAX_LOAD__SOFTCAP_NOT_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + MAX_LOAD__SOFTCAP_NOT_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + MAX_LOAD__SCALE_1_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD__SCALE_2_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD__SCALE_3_NOT_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD__MAX_VALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + MAX_LOAD__MAX_VALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + MAX_LOAD__SCALES_NOT_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + MAX_LOAD__BASESTATS_NOT_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + MAX_LOAD_SOFTCAP_SPEZIALISED_1_FOR_TOUGHNESS : int
          {static} + MAX_LOAD_SOFTCAP_SPEZIALISED_2_FOR_TOUGHNESS : int
          {static} + MAX_LOAD_SCALE_1_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD_SCALE_2_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD_SCALE_3_SPEZIALISED_FOR_TOUGHNESS : float
          {static} + MAX_LOAD_MAX_VALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + MAX_LOAD_MAX_VALUE_AFTER_SOFTCAP_2_HP_SPEZIALISED_FOR_TOUGHNESS : int
          {static} + MAX_LOAD_SCALES_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + MAX_LOAD_BASESTATS_SPEZIALISED_FORTOUGHNESS : float[]
          {static} + MAX_LOAD_SOFTCAP_NOT_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + MAX_LOAD_SOFTCAP_NOT_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + MAX_LOAD_SCALE_1_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_SCALE_2_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_SCALE_3_NOT_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_MAXVALUE_AFTER_SOFTCAP_1_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + MAX_LOAD_MAXVALUE_AFTER_SOFTCAP_2_NOT_SPEZIALISED_FOR_STRENGTH : int
          {static} + MAX_LOAD_SCALES_NOT_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + MAX_LOAD_BASES_NOT_SPEZIALISED_FOR_STREMGTH : int[]
          {static} + MAX_LOAD_SOFTCAP_SPEZIALISED_1_FOR_STRENGTH : int
          {static} + MAX_LOAD_SOFTCAP_SPEZIALISED_2_FOR_STRENGTH : int
          {static} + MAX_LOAD_SCALE_1_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_SCALE_2_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_SCALE_3_SPEZIALISED_FOR_STRENGTH : float
          {static} + MAX_LOAD_MAXVALUE_AFTER_SOFTCAP_1_SPEZIALISED_FOR_STRENGTH : int
          {static} + MAX_LOAD_MAXVALUE_AFTER_SOFTCAP_2_SPEZIALISED_FOR_STRENGTH : int
          {static} + MAX_LOAD_SCALES_SPEZIALISED_FOR_STREMGTH : float[]
          {static} + MAX_LOAD_BASES_SPEZIALISED_FOR_STREMGTH : int[]
          {static} + WEIGHT_CAP_1 : float
          {static} + WEIGHT_CAP_2 : float
          {static} + WEIGHT_CAP_3 : float
          {static} + WEIGHT_CAP_4 : float
          {static} + MINIMIN_TRAVELABEL_FIELDS : int
          {static} + NEEDED_SPEED_TO_TRAVEL_2 : int
          {static} + NEEDED_SPEED_TO_TRAVEL_3 : int
          {static} + NEEDED_SPEED_TO_TRAVEL_4 : int
          {static} + START_ATTACK_SLOTS : int
          {static} + MINIMUM_STRENGTH_1 : int
          {static} + MINIMUM_TOUGHNESS_1 : int
          {static} + MINIMUM_INTELLIGENCE_1 : int
          {static} + MINIMUM_INTELLIGENCE_2 : int
          {static} + MINIMUM_INTELLIGENCE_3 : int
          {static} + MINIMUM_MAGIC_1 : int
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
