@startuml

title __TOMBOFPIK8's Class Diagram__\n

  package model.other {
    abstract class AI {
    }
  }
  

  package model.json {
    class AdapterFactories {
    }
  }
  

  package model.items {
    class Armor {
    }
  }
  

  package model.items {
    class ArmorFactory {
    }
  }
  

  package model.items {
    enum ArmorSlot {
    }
  }
  

  package model.fighting {
    class Attack {
    }
  }
  

  package model.fighting {
    class AttackPattern {
    }
  }
  

  package utility {
    class CalculateSecondaryStats {
    }
  }
  

  package model.characters {
    class Character {
    }
  }
  

  package model.effects {
    enum Condition {
    }
  }
  

  package model.items {
    class Consumable {
    }
  }
  

  package model.items {
    enum CraftingMaterial {
    }
  }
  

  package model.effects {
    class DamageEffect {
    }
  }
  

  package model.dungeon {
    class Difficulty {
    }
  }
  

  package model.dungeon {
    class DifficultyFactory {
    }
  }
  

  package model.fighting {
    class DivineHealSkill {
    }
  }
  

  package model.dungeon {
    class Dungeon {
    }
  }
  

  package control {
    class DungeonController {
    }
  }
  

  package model.dungeon {
    class DungeonException {
    }
  }
  

  package model.dungeon {
    class DungeonFactory {
    }
  }
  

  package view {
    class DungeonPrinter {
    }
  }
  

  package model.effects {
    abstract class Effect {
    }
  }
  

  package model.effects {
    class EffectFactory {
    }
  }
  

  package constants {
    interface EffectProperties {
    }
  }
  

  package model.characters {
    class Equip {
    }
  }
  

  package model.items {
    abstract class Equipment {
    }
  }
  

  package constants {
    interface ExceptionConstants {
    }
  }
  

  package utility {
    class ExpCalculator {
    }
  }
  

  package constants {
    package constants.balancing {
      interface Factors {
      }
    }
  }
  

  package constants {
    interface FileConstants {
    }
  }
  

  package model.other {
    class GameLoaderSaver {
    }
  }
  

  package model.effects {
    class HealingEffect {
    }
  }
  

  package model.characters {
    class Hero {
    }
  }
  

  package model.characters {
    enum HeroClass {
    }
  }
  

  package view {
    class InputReader {
    }
  }
  

  package model.characters {
    class Inventory {
    }
  }
  

  package model.items {
    class InventoryFullException {
    }
  }
  

  package model.items {
    abstract class Item {
    }
  }
  

  package model.items {
    abstract class ItemFactory {
    }
  }
  

  package utility {
    class KeysForInputs {
    }
  }
  

  package model.dungeon {
    enum Landscape {
    }
  }
  

  package model.characters {
    class MobSpawner {
    }
  }
  

  package constants {
    interface ModelProperties {
    }
  }
  

  package model.dungeon {
    interface Objective {
    }
  }
  

  package view {
    package view.options {
      class Options {
      }
    }
  }
  

  package model.options {
    class Options {
    }
  }
  

  package model.overworld {
    class Overworld {
    }
  }
  

  package model.dungeon {
    class Position {
    }
  }
  

  package model.characters {
    class PrimeStats {
    }
  }
  

  package constants {
    package constants.balancing {
      interface PropertiesStats {
      }
    }
  }
  

  package model.items {
    enum Rarity {
    }
  }
  

  package model.options {
    class Resolution {
    }
  }
  

  package model.effects {
    class RootEffect {
    }
  }
  

  package model.json {
    class RuntimeTypeAdapterFactory {
    }
  }
  

  package model.other {
    class SaveState {
    }
  }
  

  package model.characters {
    class SecondaryStats {
    }
  }
  

  package model.fighting {
    abstract class Skill {
    }
  }
  

  package model.fighting {
    class SkillFactory {
    }
  }
  

  package model.fighting {
    enum SkillList {
    }
  }
  

  package model.effects {
    class SlowDownEffect {
    }
  }
  

  package model.dungeon {
    class Square {
    }
  }
  

  package utility {
    class StatBalancer {
    }
  }
  

  package model.other {
    class Statistics {
    }
  }
  

  package model.json {
    class StringForTemplateGenerator {
    }
  }
  

  package model.io {
    class TemplateReader {
    }
  }
  

  package model.dungeon {
    enum Terrain {
    }
  }
  

  package model.dungeon {
    enum TerrainObject {
    }
  }
  

  package model.dungeon {
    class Tile {
    }
  }
  

  package model.dungeon {
    class TileFactory {
    }
  }
  

  package utility {
    class TileGenerator {
    }
  }
  

  package control {
    class TombOfPik8 {
    }
  }
  

  package model.items {
    class Trinket {
    }
  }
  

  package model.items {
    class TrinketFactory {
    }
  }
  

  package view {
    class View {
    }
  }
  

  package model.options {
    class Volume {
    }
  }
  

  package model.items {
    class Weapon {
    }
  }
  

  package model.items {
    class WeaponFactory {
    }
  }
  

  package control {
    class WorldController {
    }
  }
  

  package control {
    package control.options {
      class options {
      }
    }
  }
  

  Armor -up-|> Equipment
  Armor o-- ArmorSlot : slot
  ArmorFactory -up-|> ItemFactory
  Attack o-- Effect : effect
  Attack o-- AttackPattern : attackPattern
  Character o-- Inventory : inventory
  Character o-- Equip : equip
  Character o-- SecondaryStats : secondaryStats
  Consumable -up-|> Item
  DamageEffect -up-|> Effect
  DivineHealSkill -up-|> Skill
  Dungeon o-- Objective : objective
  DungeonController o-- Dungeon : dungeon
  Equip o-- Weapon : weapon
  Equip o-- Armor : headgear
  Equip o-- Armor : chestplate
  Equip o-- Armor : legwear
  Equipment -up-|> Item
  Equipment o-- SecondaryStats : secondaryStats
  HealingEffect -up-|> Effect
  Hero -up-|> Character
  Hero o-- PrimeStats : primeStats
  Hero o-- Statistics : statistics
  Hero o-- HeroClass : heroClass
  HeroClass o-- PrimeStats : baseStats
  Item o-- Rarity : rarity
  Options -up-|> Application
  Options o-- Volume : volume
  RootEffect -up-|> Effect
  RuntimeTypeAdapterFactory -up-|> TypeAdapterFactory
  SaveState o-- Hero : player
  SaveState o-- Overworld : zaWORUDO
  SaveState o-- Difficulty : difficulty
  Skill -up-|> Attack
  SlowDownEffect -up-|> Effect
  Square o-- Terrain : terrain
  Square o-- Effect : effect
  Terrain o-- Effect : effect
  TerrainObject o-- Effect : effect
  Tile o-- Landscape : landscape
  Trinket -up-|> Equipment
  Trinket o-- PrimeStats : primeStats
  TrinketFactory -up-|> ItemFactory
  Volume -up-|> Application
  Weapon -up-|> Equipment
  WeaponFactory -up-|> ItemFactory
  WorldController o-- Overworld : overworld


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
