@startuml

title __CONSTANTS's Class Diagram__\n

  package constants {
    interface EffectProperties {
        {static} + CRUSH_EFFECT_PLUS_EFFORT : int
        {static} + DURATION_FOR_PARALYSIS_EFFECT : int
        {static} + DAMAGE_FACTOR_FOR_POISON : float
        {static} + FACTOR_FOR_SPEED_REDUCTION : float
        {static} + SMALL_HP_TO_REGAIN : int
        {static} + SMAll_HEALING_FOR_TERRAIN : int
        {static} + IRON_SIN_DURATION : int
        {static} + SUMMAND_FOR_MG_DEF : int
        {static} + FACTOR_FOR_DEF : float
        {static} + GREAT_HP_TO_HEAl : int
        {static} + DURATION_GREAT_WALL : int
        {static} + EFFORT_TO_PASS_GREAT_WALL : int
    }
  }
  

  package constants {
    interface ExceptionConstants {
        {static} + ATTACK_PATTERN_TOO_MANY_NEGATIVE_NUMBERS : String
        {static} + ATTACK_PATTERN_NO_NEGATIVE_NUMBER : String
        {static} + ATTACK_PATTERN_TO_MANY_NULL : String
        {static} + ATTACK_PATTERN_NO_NULL : String
        {static} + ATTACK_DAMAGE_IS_NEGATIVE : String
        {static} + ATTACK_MAGICAL_DAMAGE_IS_NEGATIVE : String
        {static} + ATTACK_ACCURACY_IS_NEGATIVE : String
        {static} + ATTACK_REQUIREDSLOTS_IS_NEGATIVE : String
        {static} + TOO_MANY_SKILLS : String
        {static} + FIELD_FOR_TILE_IS_NO_SQUARE : String
        {static} + FIELD_HAS_NOT_THE_RIGHT_SIZE : String
        {static} + EFFORT_IS_NEGATIVE : String
        {static} + INVENTORY_IS_FULL : String
        {static} + LEVEL_IS_NEGATIVE : String
        {static} + SQUARE_IN_TILE_IS_NULL : String
        {static} + DIFFICULTY_ARUGMENT_BELOW_ZERO : String
        {static} + MOB_LEVEL_FACTOR_NOT_IN_RANGE : String
    }
  }
  

  package constants {
    interface FileConstants {
        {static} + RESOURCE_PATH : String
        {static} + TEMPLATE_PATH : String
        {static} + OPTIONS_PATH : String
        {static} + WEAPON_TEMPLATE_PATH : String
        {static} + WEAPON_COMMON_TEMPLATES : String
        {static} + WEAPON_RARE_TEMPLATES : String
        {static} + WEAPON_EPIC_TEMPLATES : String
        {static} + WEAPON_LEGENDARY_TEMPLATES : String
        {static} + ARMOR_TEMPLATE_PATH : String
        {static} + ARMOR_COMMON_TEMPLATES : String
        {static} + ARMOR_RARE_TEMPLATES : String
        {static} + ARMOR_EPIC_TEMPLATES : String
        {static} + ARMOR_LEGENDARY_TEMPLATES : String
        {static} + TRINKET_TEMPLATE_PATH : String
        {static} + TRINKET_COMMON_TEMPLATES : String
        {static} + TRINKET_RARE_TEMPLATES : String
        {static} + TRINKET_EPIC_TEMPLATES : String
        {static} + TRINKET_LEGENDARY_TEMPLATES : String
        {static} + ATTACK_TEMPLATE_PATH : String
        {static} + SKILL_TEMPLATE_PATH : String
        {static} + MOB_TEMPLATE_PATH : String
        {static} + DUNGEON_TEMPLATE_PATH : String
        {static} + CLASS_CUSTOMIZATION_PATH : String
        {static} + WARRIOR_PATH : String
        {static} + MAGE_PATH : String
        {static} + ARCHER_PATH : String
        {static} + ASSASSIN_PATH : String
        {static} + PATH_TO_SAVING : String
        {static} + PATH_TO_SAVE_STATES : String
        {static} + PATH_TO_SAVING_OPTION : String
        {static} + PATH_TO_DIFFICULTYS : String
        {static} + PATH_TO_EASY_DIFFICULTY : String
        {static} + PATH_TO_MIDDLE_DIFFICULTY : String
        {static} + PATH_TO_HIGH_DIFFICULTY : String
        {static} + TEST_DUNGEON_PATH : String
    }
  }
  

  package constants {
    interface ModelProperties {
        {static} + MAX_SIZE_FOR_SKILLS : int
        {static} + DUNGEON_TILE_DENSITY : float
        {static} + DUNGEON_TILE_DENSITY_VARIANCE : float
        {static} + RANDOM_TILE_SIZES : int[]
        {static} + MIN_SIZE_RANDOM_DUNGEON : int
        {static} + MAX_SIZE_RANDOM_DUNGEON : int
        {static} + MAX_MOB_SPAWN_RATE_FOR_RANDOM : int
        {static} + INVENTORY_IS_INFINITE : int
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
