@startuml

title __UTILITY's Class Diagram__\n

  package utility {
    class CalculateSecondaryStats {
        - CalculateSecondaryStats()
        {static} + maxHealthByLevel()
        {static} + maxActionByLevel()
        {static} + maxEquipmentLoadByLevel()
        {static} + maxAttackByLevel()
        {static} + maxMagicAttackByLevel()
        {static} + maxDefenceByLevel()
        {static} + maxMgDefByLevel()
        {static} + attackSlotsByLevel()
        {static} + maxSpeedByLevel()
        {static} + maxTravelableFieldsByLevel()
        {static} + maxLuckByLevel()
        {static} + setMaxAttackByLevel()
        {static} + setMaxHealthByLevel()
        {static} + setMaxActionByLevel()
        {static} + setMaxStaminaByLevel()
        {static} + setMaxSpeedByLevel()
        {static} + setMaxEquipmentLoadByLevel()
        {static} + setMaxMagicalDefenceByLevel()
        {static} + setMaxMagicalAttackByLevel()
        {static} + setMaxLuckByLevel()
        {static} + setMaxDefenceByLevel()
        {static} + setMaxAttackSlotsByLevel()
        {static} + setEveryStat()
    }
  }
  

  package utility {
    class ExpCalculator {
    }
  }
  

  package utility {
    class KeysForInputs {
    }
  }
  

  package utility {
    class StatBalancer {
        {static} + balanceSecondaryStats()
        {static} + balanceSecondaryStats()
        {static} + balancePrimaryStats()
        {static} - scaleStatsToLevel()
        {static} - rollStats()
        {static} - scaleStatsToLevel()
        {static} - rollStats()
    }
  }
  

  package utility {
    class TileGenerator {
        - TileGenerator()
        {static} + generateSquaresAsTiel()
        {static} + getTile()
        {static} + getTile7x7()
        {static} - checkIfSquareIsTraversable()
        {static} - fillSquare()
        {static} - setBorders()
        {static} - fillXDimension()
        {static} - fillYDimension()
        {static} + generateTerrainOnSquare()
        {static} - fillSquaresWithStandard()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
